var geisha = [
"               xxxxxxxx                  ",
"            xxxxxxxxxxxxxx               ",
"          xxxxxxxxxxxxxxxxxx             ",
"         xxxxxxxxxxxxxxxxxxxx            ",
"        xxxxxxxxxxxxxxxxxxxxxx           ",
"       xxxxxxxxxxxxxxxxxxxxxxxx          ",
"       xxxxxxxxxxxxxxxxxxxxxxxx          ",
"     xxxxxxxx============xxxxxxxx@       ",
"   xxxxxxxx================xxxxx@xx      ",
"  xxxxxxxx==================xxx@xxxx   @@",
" xxxxxxxxx===xxxxxxxxxxxx===xx@xxxxxx@@  ",
" xxxxxxxxx=xxxxxxxxxxxxxxxx=x@xxxxx@@x   ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@@xxxx  ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@@xxxxxx  ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
"xxxxxxxxxxxx--xxxxxxxxxxx--xxxxxxxxxxxx  ",
"xxxxxxxxxxx-----xxxxxxx-----xxxxxxxxxxx  ",
"xxxxxxxxxx-------------------xxxxxxxxxx  ",
"xxxxxxx-xx-------------------xx-xxxxxxx  ",
"xxxxxx---x-------------------x---xxxxxx  ",
" xxxxx------|-------------|------xxxxx   ",
" xxxxx------|-------------|------xxxxx   ",
"  xxxxx-----|-------------|-----xxxxx    ",
"   xxxxx-----------------------xxxxx     ",
"     xxxxx-------------------xxxxx       ",
"       xxxx-----------------xxxx         ",
"            ---------------              ",
"             #-----------#               ",
"            ###---------###              ",
"           #####-------#####             ",
"          #######-----#######            ",
"         ##########--#########           ",
"         #####################           ",
"        #######################          ",
"        #######################          ",
"       #########################         ",
"       #########################         ",
"       x#######################x         ",
"       xx#####################xx         ",
"       xxxx#################xxxx         ",
"        xxx#################xxx          ",
"         xx#################xx           ",
"           #################             ",
"           #################             ",
"           #################             ",
"           #################             ",
"           #################             ",
"           #################             ",
"           #################             ",
"            ###############              "
];