var goat = [
	"       gggg            ",
	"     gggg              ", 
	"    ggg                ", 
	"  gg|gggg              ", 
	" ggggggggg          gg ", 
	" gggggggggg        gg  ", 
	"  gg  ggggggggggggggg  ", 
	"   g   gggggggggggggg  ", 
	"        ggggggggggggg  ", 
	"         gggggggggggg  ", 
	"         gg        gg  ", 
	"         gg        gg  ", 
	"         gg        gg  ",
	"         gg        gg  ",
];